import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="/joboyjs/jquery.min.js"></script>
        <script src="/joboyjs/owl.carousel.min.js"></script>

        <link rel="stylesheet" href="/joboycss/bootstrap.min.css" />
        <link rel="stylesheet" href="/joboycss/animate.css" />
        <link rel="stylesheet" href="/joboycss/app.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
